### ISSUE TITLE
Basic HTML and CSS

### ISSUE THREAD

**Issue by alexanderism55** [alexanderism55/user-api#3]
# Basic HTML and CSS

## TODO
- [x] It must have a header
- [x] It must have one input and two buttons
- [x] it Must be styled properly like the design
